name: flutterxui
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  #===================================================

  provider: ^4.0.1
  shared_preferences: ^0.5.6
  firebase_remote_config: ^0.3.0+3
  url_launcher: ^5.4.2
  transparent_image: ^1.0.0
  cached_network_image: ^2.0.0
  searchable_dropdown: ^1.1.2

  #===================================================
  flutter_screenutil: ^1.0.2
  #  slimy_card: ^1.0.2
  flutter_rating_bar: ^3.0.1+1
  percent_indicator: ^2.1.1+1
  flutter_spinkit: ^4.1.1+1
  animated_floatactionbuttons: ^0.1.0
  groovin_widgets: ^1.4.5
  flutter_icons: ^1.0.0+1
  settings_ui: ^0.2.0

  residemenu: ^1.3.5
  getflutter: ^1.0.9

  #===================================================
  curved_navigation_bar: ^0.3.2
  bottom_navy_bar: ^5.3.2
  fancy_bottom_navigation: ^0.3.2
  titled_navigation_bar: ^3.6.0
  bmnav: ^0.3.4
  flip_box_bar: ^0.9.2
  like_button: ^0.2.0




  #===================================================
  progress_dialog: ^1.2.1
  awesome_dialog: ^0.1.3
  simple_animations: ^1.3.11
  expandable: ^4.1.2
  flutter_reorderable_list: ^0.1.3
  flutter_slidable: ^0.4.4
  curved_drawer: ^0.1.2

  # flutter_test from sdk depends on quiver 2.0.5
  quiver: ^2.0.5
  intl: ^0.16.1
  flutter_login: ^1.0.14

  # this library on pub.dev says doesn't support web application but if you open github repo it does
  google_fonts: ^0.3.9




  font_awesome_flutter: ^8.5.0
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1

  share: ^0.6.3+5

  wave: ^0.0.8
  dot_pagination_swiper: ^0.1.1
  flutter_swiper: ^1.1.6

  # here i use in 3/25
  toast: ^0.1.4
  flutter_styled_toast: ^1.2.1
  load_toast: ^1.0.0
  achievement_view: ^0.2.0
  expandable_bottom_bar: ^1.0.2
  extended_navbar_scaffold: ^1.0.1
  flutter_vector_icons: ^0.2.1
  flutter_expandable_menu: ^0.0.1
  flutter_staggered_grid_view: ^0.3.0
  drag_select_grid_view: ^0.1.1
  flutter_staggered_animations: ^0.1.2
  animated_text_kit: ^2.0.0
  progress_button: ^0.0.2
  intro_views_flutter: ^2.8.0
  concentric_transition: ^0.1.1
  flutter_overboard: ^1.1.5
  package_info: ^0.4.0+17
  flutter_open_whatsapp: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    # Include all files under a subfoler by adding trailing "/":
    - assets/images/



  fonts:
    - family: Bahij Janna
      fonts:
        - asset: assets/font_family/bahij_janna_regular.ttf
    - family: Raleway Regular
      fonts:
        - asset: assets/font_family/Raleway-Regular.ttf
    - family: SFUIDisplay
      fonts:
        - asset: assets/font_family/sf-ui-display-light.otf

    - family: Canterbury
      fonts:
        - asset: assets/font_family/Canterbury.ttf

    - family: HelloStockholm
      fonts:
        - asset: assets/font_family/HelloStockholm.otf

    - family: Horizon
      fonts:
        - asset: assets/font_family/Horizon.otf

    - family: Bobbers
      fonts:
        - asset: assets/font_family/Bobbers.ttf

    - family: Agne
      fonts:
        - asset: assets/font_family/Agne.otf